name: Publish Blog on Github Pages

on:
  push:
    branches:
      - blog
  pull_request:
    branches:
      - blog

jobs:
  publish:
    name: Publish Blog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Publish pages
        uses: peaceiris/actions-gh-pages@v2.4.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
          keep_files: true
