name: Publish Github Pages
# This workflow is triggered on pushes to the repository.
on:
  push:
      branches:
        - develop
        - blog
  pull_request:
      branches:
        - develop
        - blog

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: develop
      - name: Generate public directory
        uses: ./.github/actions/generate-public-doc
      - name: Checkout blog
        uses: actions/checkout@master
        with:
          ref: blog
          path: ./public/blog
      - name: ls
        run: |
          ls
          ls public
          ls public/blog
      - name: Publish Pages
        uses: peaceiris/actions-gh-pages@v2.4.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
