name: Publish Github Pages
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Generate public directory
        uses: ./.github/actions/generate-public-doc
      - name: Publish Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: ./public
          keep_files: true
