name: Publish Github Pages
# This workflow is triggered on pushes to the repository.
on:
  push:
      branches:
        - develop

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Generate public directory
        uses: ./.github/actions/generate-public-doc
      - name: Publish pages
        uses: peaceiris/actions-gh-pages@v2.4.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./pub