name: Publish Github Pages
# This workflow is triggered on pushes to the repository.
on:
  push:
      branches:
        - develop

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/publish-github-pages
        id: publish