name: Publish Github Pages
# This workflow is triggered on pushes to the repository.
on:
  push:
      branches:
        - develop

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: peaceiris/actions-gh-pages@v2.4.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./pub
        with:
          keepFiles: true